version: '3.2'

services:

  consul:
    image: 'consul:latest'
    hostname: 'consul'
    volumes:
      - ./consul/data:/consul/data
      - ./consul/config:/consul/config 
    environment: 
      - consul
      - agent 
      - -server
      - -data-dir=/consul
      - -bootstrap-expect=1
      - -ui 
      - -client=0.0.0.0
    ports:
      - "8400:8400"
      - "8501:8501"
      - "8600:53"

  microservice_1:
    build: ./microservice_sample_1/
    hostname: microservice-1
    ports:
      - "9000:9000"
    links:
      - consul
    depends_on:
      - consul 
      
